-- quicksearch.nvim
-- A floating search launcher inspired by 99.nvim
-- Author: generated by Claude

local M = {}

-- ─────────────────────────────────────────────
-- Default config
-- ─────────────────────────────────────────────
M.config = {
  width = 60,
  height = 1,
  border = "rounded",
  title = " 🔍 QuickSearch ",
  keymap = "<leader>s",
  -- Search engines: { label, url_prefix }
  engines = {
    { key = "g", label = "Google",     url = "https://www.google.com/search?q=" },
    { key = "d", label = "DuckDuckGo", url = "https://duckduckgo.com/?q=" },
    { key = "y", label = "YouTube",    url = "https://www.youtube.com/results?search_query=" },
    { key = "r", label = "Reddit",     url = "https://www.reddit.com/search/?q=" },
    { key = "h", label = "HackerNews", url = "https://hn.algolia.com/?q=" },
    { key = "n", label = "npm",        url = "https://www.npmjs.com/search?q=" },
    { key = "p", label = "PyPI",       url = "https://pypi.org/search/?q=" },
    { key = "m", label = "MDN",        url = "https://developer.mozilla.org/en-US/search?q=" },
    { key = "s", label = "StackOverflow", url = "https://stackoverflow.com/search?q=" },
    { key = "w", label = "Wikipedia",  url = "https://en.wikipedia.org/wiki/Special:Search?search=" },
    { key = "G", label = "GitHub",     url = "https://github.com/search?q=" },
  },
  -- How to open URLs (auto-detected if nil)
  open_cmd = nil,
}

-- ─────────────────────────────────────────────
-- Helpers
-- ─────────────────────────────────────────────

-- URL-encode a string
local function urlencode(str)
  str = str:gsub("\n", " ")
  str = str:gsub("([^%w%-%.%_%~ ])", function(c)
    return string.format("%%%02X", string.byte(c))
  end)
  return str:gsub(" ", "+")
end

-- Detect the OS open command
local function detect_open_cmd()
  if M.config.open_cmd then return M.config.open_cmd end
  if vim.fn.has("mac") == 1 then return "open" end
  if vim.fn.has("win32") == 1 then return "start" end
  return "xdg-open"
end

-- Open URL in browser
local function open_url(url)
  local cmd = detect_open_cmd()
  vim.fn.jobstart({ cmd, url }, { detach = true })
  vim.notify("Opening: " .. url, vim.log.levels.INFO, { title = "QuickSearch" })
end

-- Get visual selection text
local function get_visual_selection()
  local s = vim.fn.getpos("'<")
  local e = vim.fn.getpos("'>")
  local lines = vim.fn.getregion(s, e, { type = vim.fn.visualmode() })
  return vim.fn.join(lines, " "):gsub("^%s+", ""):gsub("%s+$", "")
end

-- ─────────────────────────────────────────────
-- Engine picker (shown after text is submitted)
-- ─────────────────────────────────────────────

local function show_engine_picker(query)
  if not query or query == "" then return end

  -- Build display lines
  local lines = {}
  local max_label = 0
  for _, e in ipairs(M.config.engines) do
    if #e.label > max_label then max_label = #e.label end
  end

  for _, e in ipairs(M.config.engines) do
    local pad = string.rep(" ", max_label - #e.label)
    table.insert(lines, string.format("  [%s]  %s%s", e.key, pad, e.label))
  end

  local height = #lines + 2
  local width = max_label + 14
  local row = math.floor((vim.o.lines - height) / 2)
  local col = math.floor((vim.o.columns - width) / 2)

  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  vim.api.nvim_set_option_value("modifiable", false, { buf = buf })
  vim.api.nvim_set_option_value("buftype", "nofile", { buf = buf })

  -- Syntax highlight keys
  vim.api.nvim_buf_call(buf, function()
    vim.cmd([[syntax match QuickSearchKey /\[.\]/]])
    vim.cmd([[highlight QuickSearchKey guifg=#f7c948 gui=bold]])
    vim.cmd([[syntax match QuickSearchLabel /\]  \S.*/]])
    vim.cmd([[highlight QuickSearchLabel guifg=#a8d8a8]])
  end)

  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    row = row,
    col = col,
    width = width,
    height = height,
    border = M.config.border,
    title = string.format(' Search: "%s" ', query:sub(1, 20) .. (query:len() > 20 and "…" or "")),
    title_pos = "center",
    style = "minimal",
  })
  vim.api.nvim_set_option_value("winhl", "Normal:QuickSearchFloat,FloatBorder:QuickSearchBorder", { win = win })

  -- Map each engine key
  local opts = { nowait = true, noremap = true, silent = true }
  for _, e in ipairs(M.config.engines) do
    local url = e.url .. urlencode(query)
    vim.keymap.set("n", e.key, function()
      vim.api.nvim_win_close(win, true)
      open_url(url)
    end, vim.tbl_extend("force", opts, { buffer = buf }))
  end

  -- Close on q / Esc
  for _, k in ipairs({ "q", "<Esc>" }) do
    vim.keymap.set("n", k, function()
      vim.api.nvim_win_close(win, true)
    end, vim.tbl_extend("force", opts, { buffer = buf }))
  end

  -- Number shortcuts (1-9)
  for i, e in ipairs(M.config.engines) do
    if i <= 9 then
      local url = e.url .. urlencode(query)
      vim.keymap.set("n", tostring(i), function()
        vim.api.nvim_win_close(win, true)
        open_url(url)
      end, vim.tbl_extend("force", opts, { buffer = buf }))
    end
  end
end

-- ─────────────────────────────────────────────
-- Main floating input window
-- ─────────────────────────────────────────────

function M.open(prefill)
  local width = M.config.width
  local row = math.floor((vim.o.lines - 3) / 2)
  local col = math.floor((vim.o.columns - width) / 2)

  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_set_option_value("buftype", "prompt", { buf = buf })

  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    row = row,
    col = col,
    width = width,
    height = M.config.height,
    border = M.config.border,
    title = M.config.title,
    title_pos = "center",
    style = "minimal",
  })

  vim.api.nvim_set_option_value("winhl", "Normal:QuickSearchFloat,FloatBorder:QuickSearchBorder", { win = win })

  -- Prompt setup
  vim.fn.prompt_setprompt(buf, " ")

  -- Start insert mode
  vim.cmd("startinsert!")

  -- Prefill text (e.g. visual selection)
  if prefill and prefill ~= "" then
    vim.api.nvim_feedkeys(prefill, "i", false)
  end

  -- On confirm (Enter)
  vim.fn.prompt_setcallback(buf, function(text)
    vim.api.nvim_win_close(win, true)
    local query = text:gsub("^%s+", ""):gsub("%s+$", "")
    if query ~= "" then
      show_engine_picker(query)
    end
  end)

  -- Close on Esc
  vim.keymap.set("i", "<Esc>", function()
    vim.api.nvim_win_close(win, true)
  end, { buffer = buf, silent = true })

  -- Ctrl+C also closes
  vim.keymap.set("i", "<C-c>", function()
    vim.api.nvim_win_close(win, true)
  end, { buffer = buf, silent = true })
end

-- Open with current word under cursor as prefill
function M.open_word()
  local word = vim.fn.expand("<cword>")
  M.open(word)
end

-- Open with visual selection as prefill
function M.open_visual()
  local sel = get_visual_selection()
  M.open(sel)
end

-- ─────────────────────────────────────────────
-- Setup
-- ─────────────────────────────────────────────

function M.setup(opts)
  M.config = vim.tbl_deep_extend("force", M.config, opts or {})

  -- Highlight groups (set once, respect colorscheme overrides)
  vim.api.nvim_set_hl(0, "QuickSearchFloat",  { bg = "#1a1b26", fg = "#c0caf5" })
  vim.api.nvim_set_hl(0, "QuickSearchBorder", { fg = "#7aa2f7" })

  -- Commands
  vim.api.nvim_create_user_command("QuickSearch",       function() M.open() end, {})
  vim.api.nvim_create_user_command("QuickSearchWord",   function() M.open_word() end, {})
  vim.api.nvim_create_user_command("QuickSearchVisual", function() M.open_visual() end, { range = true })

  -- Keymaps
  local key = M.config.keymap
  vim.keymap.set("n", key,        M.open,        { desc = "QuickSearch: open" })
  vim.keymap.set("n", key .. "w", M.open_word,   { desc = "QuickSearch: search word under cursor" })
  vim.keymap.set("v", key,        M.open_visual, { desc = "QuickSearch: search visual selection" })
end

return M
